'use client';
import {useEffect,useState} from 'react';
import {ArrowRight,CalendarDays,Check,Cloud,LogOut,Plus,UserRound,Volume2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {PortalShell,useAccountLanguage} from './account-shell';
import {accountFetch,jsonAction,loadAccount,signedOut,type AccountOverview} from '../../lib/customer-client';

export default function AccountDashboard(){
  const {lang,setLang,m}=useAccountLanguage();const [account,setAccount]=useState<AccountOverview>(signedOut),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[add,setAdd]=useState(false),[importChild,setImportChild]=useState('');
  async function refresh(){try{setAccount(await loadAccount());setError('');}catch(e){setError(e instanceof Error?e.message:m.serviceError);}finally{setLoaded(true);}}
  useEffect(()=>{void refresh();},[]);
  async function addChild(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);try{await jsonAction('/api/account/child',Object.fromEntries(new FormData(event.currentTarget)));setAdd(false);await refresh();}catch(e){setError(e instanceof Error?e.message:m.serviceError);}finally{setBusy(false);}}
  async function requestAccess(){setBusy(true);try{await jsonAction('/api/account/request',{});setMessage(lang==='id'?'Permintaan tersimpan. Pembayaran akan diperiksa pengelola sebelum akses diaktifkan. Belum ada tagihan otomatis.':'Request saved. The owner will review payment before activating access. No automatic charge was made.');}catch(e){setError(e instanceof Error?e.message:m.serviceError);}finally{setBusy(false);}}
  async function importHistory(){setBusy(true);try{
    const response=await accountFetch('/api/account/workbook?child='+importChild);const current:any=await response.json();if(!response.ok)throw new Error(current.error);
    if(current.payload)throw new Error('Profil ini sudah memiliki riwayat akun. Pilih profil baru agar riwayat tidak tertimpa.');
    const family=JSON.parse(localStorage.getItem('little-world-v1')||'null'),book=JSON.parse(localStorage.getItem('astra-workbook-v2')||'null'),learning=JSON.parse(localStorage.getItem('littlefinger-learning-v1')||'{"version":1,"events":[],"previous":[]}');
    if(!family||!book)throw new Error('Tidak ada riwayat lama yang ditemukan di browser ini.');
    await jsonAction('/api/account/workbook',{child:importChild,revision:current.revision,payload:{family,book,learning}});setImportChild('');setMessage('Riwayat perangkat berhasil disalin ke profil anak yang dipilih.');
  }catch(e){setError(e instanceof Error?e.message:m.serviceError);}finally{setBusy(false);}}
  const expired=!!account.subscription?.access_expires_at&&new Date(account.subscription.access_expires_at).getTime()<=Date.now();
  const suspended=account.account?.account_status&&account.account.account_status!=='active';
  const state=suspended?m.statusSuspended:account.access?m.statusActive:expired?m.statusExpired:m.statusPreorderPending;
  const date=(value:string|null|undefined)=>value?new Intl.DateTimeFormat(lang==='id'?'id-ID':lang==='zh'?'zh-CN':lang,{dateStyle:'long'}).format(new Date(value)):'—';
  return <PortalShell lang={lang} setLang={setLang}><main className="lf-dashboard"><div className="lf-dashboard-heading"><div><span className="lf-kicker">{m.account}</span><h1>{account.profile?.full_name||m.dashboard}</h1><p>{account.user?.email}</p></div>{account.user&&<button className="text-button" disabled={busy} onClick={async()=>{setBusy(true);try{const data=await jsonAction('/api/auth/logout',{});location.assign('/login'+(data.revoked?'':'?logout=partial'));}catch(e){setError(e instanceof Error?e.message:m.serviceError);}finally{setBusy(false);}}}><LogOut size={17}/>{m.logout}</button>}</div>{error&&<p className="lf-error" role="alert">{error} <button onClick={refresh}>{m.loading.replace('…','')} ↻</button></p>}{message&&<p className="lf-account-success" role="status">{message}</p>}
    {!loaded?<p>{m.loading}</p>:!account.user?<section className="lf-account-card"><h2>{m.loginCta}</h2><p>{m.cloudProgressHint}</p><a className="lf-primary" href="/login">{m.login}</a><a className="lf-secondary" href="/register">{m.register}</a></section>:<>
      <section className="lf-subscription-card"><div><span className={'lf-status '+(account.access?'active':'')}>{account.access&&<Check size={15}/>} {state}</span><h2>{m.accessDuration}</h2><p>{suspended?m.suspendedMessage:account.access?m.activeMessage.replace('{{access_expires_at}}',date(account.subscription?.access_expires_at)):expired?m.expiredMessage:m.pendingMessage}</p><p className="lf-small-note">{m.activationNote}</p></div><div className="lf-access-dates"><CalendarDays size={25}/><span>{m.accessStarts}<strong>{date(account.subscription?.access_starts_at)}</strong></span><span>{m.accessExpires}<strong>{date(account.subscription?.access_expires_at)}</strong></span><Button className="lf-primary" disabled={busy||!!suspended} onClick={requestAccess}>{account.subscription?.access_starts_at?m.renewCta:m.preorderCta}</Button></div></section>
      <section className="lf-children"><div className="lf-section-row"><h2>{m.children}</h2><Button variant="outline" onClick={()=>setAdd(true)}><Plus size={17}/>{m.saveChild}</Button></div><div className="lf-child-grid">{account.children.map(child=><article className="lf-account-card" key={child.id}><span className="lf-child-avatar"><UserRound size={28}/></span><h3>{child.display_name}</h3><p>{child.age_band} · {child.preferred_language.toUpperCase()}</p><a className="lf-primary" href={'/?child='+child.id+'#collection'}>{account.access?m.continueCta:m.activitiesPreview}<ArrowRight size={17}/></a><a className="lf-secondary" href={'/?child='+child.id+'#report'}>{m.progress}</a>{account.access&&<button className="text-button" onClick={()=>{setError('');setImportChild(child.id);}}>Impor riwayat perangkat</button>}</article>)}</div>{!account.children.length&&<p>{lang==='id'?'Tambahkan nama panggilan dan rentang usia anak untuk menyiapkan ruang bermainnya.':'Add your child’s preferred name and age range to prepare their playroom.'}</p>}</section>
      <section className="lf-account-tools"><a href="/parent-voice"><Volume2/><span>Suara orang tua<small>Rekam petunjuk dengan suara keluarga.</small></span><ArrowRight/></a><div><Cloud/><span>{m.cloudProgress}<small>{m.cloudProgressHint}</small></span></div>{account.account?.admin_role&&<a href="/account/admin"><span>{m.adminSubscriptions}</span><ArrowRight/></a>}</section>
      <details className="lf-account-preferences"><summary>{m.privacy}</summary><p>{m.marketingConsent}</p><button className="lf-secondary" disabled={busy} onClick={async()=>{setBusy(true);try{await jsonAction('/api/account/marketing',{consent:false});setMessage(m.statusUnsubscribed);}catch(e){setError(e instanceof Error?e.message:m.serviceError);}finally{setBusy(false);}}}>{m.statusUnsubscribed}</button></details>
    </>}
    <Dialog open={add} onOpenChange={setAdd}><DialogContent><DialogTitle>{m.children}</DialogTitle><DialogDescription>{m.childName}</DialogDescription><form onSubmit={addChild} className="lf-account-form"><label htmlFor="new-child-name">{m.childName}</label><Input id="new-child-name" name="name" required maxLength={60}/><label htmlFor="new-child-age">{m.childAge}</label><select id="new-child-age" name="age">{['2-3','3-4','4-5','5-6'].map(a=><option key={a}>{a}</option>)}</select><label htmlFor="new-child-language">{m.preferredLanguage}</label><select id="new-child-language" name="language" defaultValue={lang}><option value="id">Indonesia</option><option value="en">English</option><option value="zh">中文</option><option value="ar">العربية</option></select><Button className="lf-primary" disabled={busy}>{busy?m.saving:m.saveChild}</Button></form></DialogContent></Dialog>
    <Dialog open={!!importChild} onOpenChange={v=>{if(!v)setImportChild('');}}><DialogContent><DialogTitle>Salin riwayat perangkat?</DialogTitle><DialogDescription>Pastikan aktivitas yang tersimpan di browser ini memang milik {account.children.find(c=>c.id===importChild)?.display_name}. Riwayat tidak dipindahkan otomatis antar akun.</DialogDescription><p>Impor hanya tersedia untuk profil yang belum memiliki riwayat di akun.</p>{error&&<p className="lf-error" role="alert">{error}</p>}<Button className="lf-primary" disabled={busy} onClick={importHistory}>Ya, salin ke profil ini</Button></DialogContent></Dialog>
  </main></PortalShell>;
}
