'use client';
import {useEffect,useState} from 'react';
import {Search,ArrowLeft,ShieldCheck} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {accountFetch,jsonAction,loadAccount} from '../../lib/customer-client';
import {PortalShell,useAccountLanguage} from './account-shell';
type Row={id:string;full_name:string;email:string;whatsapp_e164:string;account_status:string;admin_role:boolean;subscription:{status:string;access_starts_at:string|null;access_expires_at:string|null}|null;request:{request_type:string}|null};
export default function AccountAdmin(){
 const {lang,setLang}=useAccountLanguage();const [allowed,setAllowed]=useState<boolean|null>(null),[rows,setRows]=useState<Row[]>([]),[query,setQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<Row|null>(null),[confirmed,setConfirmed]=useState(false),[key,setKey]=useState('');
 async function refresh(){setBusy(true);try{const response=await accountFetch('/api/account-admin/customers?q='+encodeURIComponent(query));const data:any=await response.json();if(!response.ok)throw new Error(data.error);setRows(data);setError('');}catch(e){setError(e instanceof Error?e.message:'Daftar belum dapat dimuat.');}finally{setBusy(false);}}
 useEffect(()=>{loadAccount().then(a=>{setAllowed(!!a.account?.admin_role);if(a.account?.admin_role)void refresh();}).catch(()=>setAllowed(false));},[]);
 async function activate(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!selected||!confirmed)return;setBusy(true);setError('');try{const form=Object.fromEntries(new FormData(event.currentTarget));await jsonAction('/api/account-admin/subscription',{user:selected.id,action:selected.subscription?.access_starts_at?'renew':'activate',reference:form.reference,amount:Number(form.amount),key,confirmed});setSelected(null);await refresh();}catch(e){setError(e instanceof Error?e.message:'Aktivasi belum diproses.');}finally{setBusy(false);}}
 const date=(v:string|null|undefined)=>v?new Date(v).toLocaleDateString('id-ID',{dateStyle:'medium'}):'Belum aktif';
 return <PortalShell lang={lang} setLang={setLang}><main className="lf-dashboard"><a className="text-button" href="/account"><ArrowLeft size={17}/>Kembali ke akun</a><div className="lf-dashboard-heading"><div><span className="lf-kicker">PENGELOLA</span><h1>Akses keluarga</h1><p>Aktifkan hanya setelah pembayaran diperiksa. Setiap perubahan tercatat.</p></div><ShieldCheck size={35}/></div>{allowed===null?<p>Memeriksa akun…</p>:!allowed?<section className="lf-account-card"><h2>Akses khusus pengelola</h2><p>Masuk dengan email pemilik yang telah diverifikasi.</p><a className="lf-primary" href="/login">Masuk</a></section>:<><form className="lf-admin-search" onSubmit={e=>{e.preventDefault();void refresh();}}><Input aria-label="Cari nama, email, atau WhatsApp" placeholder="Cari nama, email, atau WhatsApp" value={query} onChange={e=>setQuery(e.target.value)} maxLength={100}/><Button type="submit" disabled={busy}><Search size={18}/>Cari</Button></form>{error&&<p className="lf-error" role="alert">{error}</p>}<div className="lf-admin-table"><table><thead><tr><th>Keluarga</th><th>Status</th><th>Masa akses</th><th>Tindakan</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.full_name}</strong><span>{row.email}</span><span>{row.whatsapp_e164}</span></td><td>{row.account_status}<br/>{row.request&&<small>Permintaan {row.request.request_type==='renew'?'perpanjangan':'aktivasi'}</small>}</td><td>{date(row.subscription?.access_starts_at)}<br/>{date(row.subscription?.access_expires_at)}</td><td><Button variant="outline" disabled={busy||row.account_status!=='active'} onClick={()=>{setConfirmed(false);setKey(crypto.randomUUID());setSelected(row);}}>{row.subscription?.access_starts_at?'Perpanjang 365 hari':'Aktifkan 365 hari'}</Button></td></tr>)}</tbody></table></div>{!rows.length&&<p>Belum ada akun yang sesuai. Akun muncul setelah email terverifikasi dan orang tua masuk.</p>}</>}
 <Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null);}}><DialogContent><DialogTitle>{selected?.subscription?.access_starts_at?'Perpanjang akses':'Aktifkan akses'} · {selected?.full_name}</DialogTitle><DialogDescription>Akses baru berlaku 365 hari sejak aktivasi. Perpanjangan yang dilakukan sebelum kedaluwarsa menambah 365 hari dari tanggal berakhir, sehingga sisa hari tidak hilang.</DialogDescription><form onSubmit={activate} className="lf-account-form"><label htmlFor="payment-reference">Referensi pembayaran</label><Input id="payment-reference" name="reference" required minLength={3} maxLength={200}/><label htmlFor="paid-amount">Nominal yang telah diterima</label><select id="paid-amount" name="amount"><option value="39000">Rp39.000 · preorder</option><option value="55000">Rp55.000 · reguler</option></select><label className="lf-consent"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)}/><span>Saya sudah memeriksa pembayaran dan identitas keluarga ini.</span></label>{error&&<p className="lf-error" role="alert">{error}</p>}<Button className="lf-primary" disabled={busy||!confirmed}>{busy?'Menyimpan…':'Konfirmasi akses 365 hari'}</Button></form></DialogContent></Dialog></main></PortalShell>;
}
