'use client';
import {useState} from 'react';
import {ArrowLeft,Check,BookOpen,Trophy,CalendarDays,Download} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {Art} from './artwork';
import {categories} from '../data/workbook';
import {localDay,summarize,type LearningLog} from '../data/daily-report';

export default function DailyReport({log,nickname,onBack}:{log:LearningLog;nickname:string;onBack:()=>void}){
 const [day,setDay]=useState(localDay()),r=summarize(log,day),cat=(id:string)=>categories.find(c=>c.id===id);
 const download=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({product:'Littlefinger Activities',day,child:nickname,report:r},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`littlefinger-report-${day}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 return <section className="daily-report collection-page"><button className="text-button" onClick={onBack}><ArrowLeft size={18}/>Kembali bermain</button><header className="report-heading"><span className="eyebrow">CATATAN BERMAIN</span><h1>Langkah kecil {nickname&&nickname!=='Little explorer'?nickname:'si kecil'}</h1><p>Lihat yang dicoba, yang berhasil, dan yang ingin diulang.</p><label className="report-date"><CalendarDays size={19}/><span>Tanggal</span><Input type="date" aria-label="Tanggal laporan" value={day} max={localDay()} onChange={e=>setDay(e.target.value||localDay())}/></label></header>
 <div className="report-kpis">{[[Check,r.correct,'Jawaban benar',`${r.firstTry} tanpa koreksi`],[BookOpen,r.completed,'Bagian selesai',`${r.sheets} worksheet tuntas`],[Trophy,r.newWins,'Pencapaian baru','Bagian yang baru pertama selesai'],[CalendarDays,r.attempts,'Jawaban diperiksa',`${r.tried} bagian dinilai`]].map(([Icon,n,title,detail],i)=>{const I=Icon as typeof Check;return <article key={i}><I size={21}/><strong>{n as number}</strong><h2>{title as string}</h2><p>{detail as string}</p></article>})}</div>
 {!r.completed&&!r.attempts&&!r.categories.length?<div className="report-empty"><Art name="sprout"/><h2>Belum ada catatan hari ini.</h2><p>Mulai satu aktivitas. Catatan akan terisi otomatis saat anak bermain dan memeriksa jawaban.</p><button className="finish-button" onClick={onBack}>Pilih aktivitas</button></div>:<><div className="report-insights"><article><h2>Terlihat kuat hari ini</h2>{r.strong.length?r.strong.slice(0,3).map(c=><div className="report-highlight" key={c.id}><Art name={cat(c.id)?.asset||'star'}/><div><strong>{cat(c.id)?.title.id}</strong><p>{c.firstTry} dari {c.tried} bagian benar tanpa koreksi.</p></div></div>):<p>Belum cukup percobaan. Bagian ini muncul setelah minimal 3 bagian dalam satu kategori dicoba.</p>}</article><article><h2>Sering dipilih & berhasil</h2>{r.interests.length?r.interests.slice(0,3).map(c=><div className="report-highlight" key={c.id}><Art name={cat(c.id)?.asset||'leaf'}/><div><strong>{cat(c.id)?.title.id}</strong><p>{c.opens} kali dibuka · {c.correct} jawaban benar</p></div></div>):<p>Minat mulai terlihat ketika kategori dibuka kembali dan beberapa jawabannya benar.</p>}</article></div><div className="report-breakdown"><h2>Perjalanan per kategori</h2>{r.categories.map(c=><article key={c.id}><Art name={cat(c.id)?.asset||'leaf'}/><div><h3>{cat(c.id)?.title.id||c.id}</h3><p>{c.opens} kunjungan · {c.completed} bagian selesai</p></div><strong>{c.correct}/{c.tried}<small>benar / dinilai</small></strong></article>)}</div></>}
 <details className="report-explainer"><summary>Cara membaca laporan</summary><p>Satu jawaban benar berarti satu bagian dengan jawaban yang cocok, walaupun ada beberapa gambar yang dipilih. Mengulang bagian yang sama tidak menambah jumlah benar atau selesai pada hari yang sama.</p><p>“Tanpa koreksi” berarti percobaan pertama hari ini benar tanpa salah pasangan atau kartu. Percobaan yang belum selesai dari hari sebelumnya tetap membawa catatan koreksinya. Gambar bebas, tracing, dan eksplorasi bersama dihitung sebagai kegiatan selesai, bukan jawaban benar. Hari ini ada {r.creative} bagian kreatif.</p><p>Satu worksheet tuntas ketika seluruh bagiannya sudah selesai. Pencapaian baru menghitung bagian yang belum pernah selesai sebelumnya. Data lama yang tidak memiliki tanggal tidak dimasukkan ke laporan harian.</p><p>Laporan mencatat worksheet buku aktivitas. Catatan memakai tanggal perangkat dan tersimpan di peramban ini. Ini gambaran kegiatan bermain bersama, bukan tes kemampuan atau penilaian perkembangan. Satu profil digunakan pada perangkat ini.</p></details><button className="soft-button" onClick={download}><Download size={17}/>Simpan laporan hari ini</button>
 </section>;
}
