'use client';
import {useEffect,useRef,useState} from 'react';
import {Mic,Square,Upload,Save,Trash2,Volume2,ArrowLeft} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import type {AudioLang} from '../data/types';
const words={id:{record:'Rekam suaraku',title:'Suara orang tua',read:'Bacakan kalimat ini persis, termasuk nama anak.',start:'Mulai merekam',stop:'Hentikan rekaman',upload:'Unggah audio',save:'Simpan rekaman',saving:'Menyimpan…',cancel:'Batal',delete:'Hapus rekaman',confirm:'Hapus rekaman ini?',removed:'Rekaman yang dihapus akan kembali memakai suara perangkat.',saved:'Rekaman tersimpan.',privacy:'Rekaman disimpan pribadi untuk akunmu. Maksimal 60 detik dan 5 MB. Rekam tiap bahasa secara terpisah; suara tidak dikloning atau diterjemahkan otomatis.',error:'Mikrofon belum bisa digunakan. Izinkan akses mikrofon atau unggah file audio.',long:'Gunakan rekaman maksimal 60 detik dan 5 MB.',invalid:'File audio belum bisa diputar. Coba format lain.',required:'Rekam atau unggah audio terlebih dahulu.',signin:'Masuk dengan ChatGPT',back:'Kembali bermain',library:'Koleksi suara orang tua',empty:'Belum ada rekaman di bahasa ini.',hint:'Aktifkan mode rekam di pengaturan, lalu ketuk mikrofon di samping pertanyaan atau nama gambar. Nama dan bahasa yang berbeda memakai rekaman berbeda.'},
 en:{record:'Record my voice',title:'Parent voice',read:'Read this exact sentence, including your child’s name.',start:'Start recording',stop:'Stop recording',upload:'Upload audio',save:'Save recording',saving:'Saving…',cancel:'Cancel',delete:'Delete recording',confirm:'Delete this recording?',removed:'Deleted recordings will use the device voice again.',saved:'Recording saved.',privacy:'Recordings are private to your account. Up to 60 seconds and 5 MB. Record each language separately; your voice is not cloned or automatically translated.',error:'Microphone unavailable. Allow microphone access or upload audio.',long:'Use a recording up to 60 seconds and 5 MB.',invalid:'This audio file cannot play. Try another format.',required:'Record or upload audio first.',signin:'Sign in with ChatGPT',back:'Back to play',library:'Parent voice collection',empty:'No recordings in this language yet.',hint:'Enable recording mode in settings, then tap the microphone beside a question or picture name. Different names and languages use separate recordings.'},
 zh:{record:'录下我的声音',title:'家长的声音',read:'请准确读出这句话，包括孩子的名字。',start:'开始录音',stop:'停止录音',upload:'上传音频',save:'保存录音',saving:'正在保存…',cancel:'取消',delete:'删除录音',confirm:'删除这段录音？',removed:'删除后将使用设备声音。',saved:'录音已保存。',privacy:'录音仅供你的账户使用。每段最多60秒、5 MB。每种语言需要分别录音，不会克隆声音或自动翻译。',error:'无法使用麦克风。请允许访问麦克风或上传音频。',long:'录音不得超过60秒和5 MB。',invalid:'无法播放这段音频。请尝试其他格式。',required:'请先录制或上传音频。',signin:'使用ChatGPT登录',back:'返回游戏',library:'家长录音库',empty:'此语言还没有录音。',hint:'在设置中开启录音模式，然后点击问题或图片名称旁的麦克风。不同名字和语言使用不同录音。'},
 ar:{record:'تسجيل صوتي',title:'صوت الوالدين',read:'يرجى قراءة هذه الجملة كما هي، بما فيها اسم الطفل.',start:'بدء التسجيل',stop:'إيقاف التسجيل',upload:'رفع ملف صوتي',save:'حفظ التسجيل',saving:'جارٍ الحفظ…',cancel:'إلغاء',delete:'حذف التسجيل',confirm:'حذف هذا التسجيل؟',removed:'سيُستخدم صوت الجهاز بعد حذف التسجيل.',saved:'تم حفظ التسجيل.',privacy:'التسجيلات خاصة بحسابك. الحد الأقصى 60 ثانية و5 ميغابايت. تُسجّل كل لغة على حدة، ولا يُستنسخ الصوت أو يُترجم تلقائيًا.',error:'الميكروفون غير متاح. يرجى السماح باستخدامه أو رفع ملف صوتي.',long:'الحد الأقصى للتسجيل 60 ثانية و5 ميغابايت.',invalid:'تعذر تشغيل الملف الصوتي. يرجى تجربة صيغة أخرى.',required:'يرجى تسجيل صوت أو رفع ملف أولًا.',signin:'تسجيل الدخول باستخدام ChatGPT',back:'العودة إلى اللعب',library:'مجموعة أصوات الوالدين',empty:'لا توجد تسجيلات بهذه اللغة بعد.',hint:'يمكن تفعيل وضع التسجيل في الإعدادات، ثم الضغط على الميكروفون بجانب السؤال أو اسم الصورة. لكل اسم ولغة تسجيل مختلف.'}};
export function RecordVoiceButton({text,lang,onSaved}:{text:string;lang:AudioLang;onSaved?:()=>void}){
 const w=words[lang],[open,setOpen]=useState(false),[recording,setRecording]=useState(false),[requesting,setRequesting]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[clip,setClip]=useState<Blob|null>(null),[url,setUrl]=useState(''),[seconds,setSeconds]=useState(0);
 const stream=useRef<MediaStream|null>(null),recorder=useRef<MediaRecorder|null>(null),timer=useRef<ReturnType<typeof setInterval>|null>(null),alive=useRef(true),attempt=useRef(0);
 const cleanup=()=>{attempt.current++;if(timer.current)clearInterval(timer.current);timer.current=null;if(recorder.current&&recorder.current.state!=='inactive')recorder.current.stop();stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;recorder.current=null};
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;cleanup()}},[]);
 useEffect(()=>{cleanup();setRecording(false);setRequesting(false);setClip(null);setMessage('')},[text,lang]);
 useEffect(()=>{if(!clip){setUrl('');return}const value=URL.createObjectURL(clip);setUrl(value);return()=>URL.revokeObjectURL(value)},[clip]);
 const close=(value:boolean)=>{if(!value){cleanup();setRecording(false);setRequesting(false);setClip(null);setMessage('')}setOpen(value)};
 const start=async()=>{setRequesting(true);setMessage('');setClip(null);window.dispatchEvent(new Event('littlefinger-stop-audio'));const token=++attempt.current;try{if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined')throw new Error();const input=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current||token!==attempt.current){input.getTracks().forEach(t=>t.stop());return}stream.current=input;const mime=['audio/webm;codecs=opus','audio/mp4','audio/ogg;codecs=opus'].find(x=>MediaRecorder.isTypeSupported(x));const r=new MediaRecorder(input,mime?{mimeType:mime}:undefined),chunks:BlobPart[]=[];recorder.current=r;r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};r.onerror=()=>{input.getTracks().forEach(t=>t.stop());if(alive.current&&token===attempt.current){cleanup();setRecording(false);setRequesting(false);setMessage(w.error)}};r.onstop=()=>{input.getTracks().forEach(t=>t.stop());if(alive.current&&token===attempt.current){if(timer.current)clearInterval(timer.current);timer.current=null;setClip(new Blob(chunks,{type:r.mimeType||'audio/webm'}));setRecording(false)}};r.start();setRequesting(false);setRecording(true);setSeconds(0);let count=0;timer.current=setInterval(()=>{count++;setSeconds(count);if(count>=60&&r.state==='recording')r.stop()},1000)}catch{if(alive.current&&token===attempt.current){cleanup();setRequesting(false);setRecording(false);setMessage(w.error)}}};
 const upload=async(file:File|undefined)=>{if(!file)return;const token=++attempt.current;setMessage('');setClip(null);if(file.size>5_000_000){setMessage(w.long);return}const u=URL.createObjectURL(file),audio=new Audio();audio.preload='metadata';audio.onloadedmetadata=()=>{if(alive.current&&token===attempt.current){if(!Number.isFinite(audio.duration)||audio.duration<=0)setMessage(w.invalid);else if(audio.duration>60)setMessage(w.long);else setClip(file)}URL.revokeObjectURL(u)};audio.onerror=()=>{if(alive.current&&token===attempt.current)setMessage(w.invalid);URL.revokeObjectURL(u)};audio.src=u};
 const save=async()=>{if(!clip){setMessage(w.required);return}if(clip.size>5_000_000){setMessage(w.long);return}const token=attempt.current;setBusy(true);setMessage('');try{const data=new FormData();data.set('lang',lang);data.set('text',text);data.set('audio',clip,'parent-recording');const r=await fetch('/api/parent-voice',{method:'PUT',body:data});const body=await r.json() as {error?:string};if(r.ok)window.dispatchEvent(new Event('littlefinger-voice-updated'));if(!alive.current||token!==attempt.current)return;if(!r.ok){setMessage(r.status===401?w.signin:body.error||w.error);return}setMessage(w.saved);onSaved?.()}catch{if(alive.current&&token===attempt.current)setMessage(w.error)}finally{if(alive.current)setBusy(false)}};
 return <><button type="button" data-voice-control className="record-voice-button" aria-label={w.record+': '+text} disabled={!text} onClick={e=>{e.stopPropagation();setOpen(true)}}><Mic size={16}/></button><Dialog open={open} onOpenChange={close}><DialogContent className="record-dialog" dir={lang==='ar'?'rtl':'ltr'}><DialogTitle>{w.title}</DialogTitle><DialogDescription>{w.read}</DialogDescription><blockquote lang={lang}>{text}</blockquote><p className="record-privacy">{w.privacy}</p><div className="record-actions"><button className={recording?'finish-button recording':'finish-button'} disabled={busy||requesting} onClick={()=>recording?recorder.current?.stop():start()}>{recording?<Square size={18}/>:<Mic size={18}/>} {recording?`${w.stop} · ${seconds}s`:w.start}</button><label className="soft-button"><Upload size={17}/>{w.upload}<input type="file" accept="audio/*" disabled={busy||recording||requesting} onChange={e=>{void upload(e.target.files?.[0]);e.target.value=''}}/></label></div>{url&&<audio controls src={url} onPlay={()=>window.dispatchEvent(new Event('littlefinger-stop-audio'))}/>}<p role="status">{message}</p>{message===w.signin&&<a href="/parent-voice" target="_top">{w.signin}</a>}<button className="finish-button" disabled={!clip||busy||recording||requesting} onClick={save}><Save size={17}/>{busy?w.saving:w.save}</button></DialogContent></Dialog></>;
}
export default function ParentVoiceLibrary(){
 const [lang,setLang]=useState<AudioLang>('id'),[rows,setRows]=useState<{key:string;text:string;updatedAt:string;language:string}[]>([]),[error,setError]=useState(''),[revision,setRevision]=useState(0),w=words[lang];
 useEffect(()=>{let cancelled=false;fetch('/api/parent-voice?list=1&lang='+lang).then(async r=>{if(!r.ok)throw new Error();const data=await r.json() as {recordings:typeof rows};if(!cancelled){setRows(data.recordings.map(row=>({...row,language:lang})));setError('')}}).catch(()=>{if(!cancelled)setError(w.error)});return()=>{cancelled=true}},[lang,revision]);
 const remove=async(key:string,language:string)=>{try{const r=await fetch('/api/parent-voice',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({lang:language,key})});if(!r.ok)throw new Error();setRows(v=>v.filter(x=>x.key!==key||x.language!==language));window.dispatchEvent(new Event('littlefinger-voice-updated'))}catch{setError(w.error)}};
 return <main className="parent-voice-library" dir={lang==='ar'?'rtl':'ltr'}><a className="text-button" href="/"><ArrowLeft size={18}/>{w.back}</a><h1>{w.library}</h1><p>{w.hint}</p><label>Bahasa · Language <select value={lang} onChange={e=>{setRows([]);setError('');setLang(e.target.value as AudioLang)}}><option value="id">Indonesia</option><option value="en">English</option><option value="zh">中文</option><option value="ar">العربية</option></select></label><p role="status">{error}</p>{!rows.length&&!error&&<p>{w.empty}</p>}{rows.map(row=><article key={row.key}><p>{row.text}</p><audio controls preload="none" src={'/api/parent-voice?lang='+lang+'&key='+row.key}/><div className="record-actions"><RecordVoiceButton text={row.text} lang={lang} onSaved={()=>setRevision(v=>v+1)}/><AlertDialog><AlertDialogTrigger asChild><button className="text-button"><Trash2 size={16}/>{w.delete}</button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{w.confirm}</AlertDialogTitle><AlertDialogDescription>{w.removed}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{w.cancel}</AlertDialogCancel><AlertDialogAction onClick={()=>remove(row.key,row.language)}>{w.delete}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div></article>)}</main>;
}
