'use client';
import {useState} from 'react';
import {ArrowRight,Check,Volume2,BarChart3,Heart,MessageCircle,Leaf} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Button} from '@/components/ui/button';
import {Art} from './artwork';
import catalogueStats from '../../public/specs/learning-paths-coverage.json';
import {activityKinds} from '../data/activity-kinds';
import {preorderSchema} from '../../lib/preorder';

export function Brand(){return <span className="brand-lockup"><Art name="sun"/><span>littlefinger<small>ACTIVITIES</small></span></span>}
export default function Preorder(){
 const [name,setName]=useState(''),[whatsapp,setWhatsApp]=useState(''),[consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[success,setSuccess]=useState(false),[groupUrl,setGroupUrl]=useState<string|null>(null);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setError('');const parsed=preorderSchema.safeParse({name,whatsapp,consent,website:new FormData(e.currentTarget).get('website')||''});if(!parsed.success){setError(parsed.error.issues[0].message);return}setBusy(true);try{const response=await fetch('/api/preorder',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(parsed.data)});const data=await response.json() as {ok?:boolean;error?:string;groupUrl?:string};if(!response.ok||!data.ok)throw new Error(data.error||'Pendaftaran belum tersimpan.');setGroupUrl(data.groupUrl||null);setSuccess(true)}catch(err){setError(err instanceof Error?err.message:'Koneksi terputus. Silakan coba lagi.')}finally{setBusy(false)}}
 const faq=[['Apa yang didapat dengan Rp39.000?','Harga preorder untuk akses satu tahun sejak akun diaktifkan setelah peluncuran. Harga reguler yang direncanakan Rp55.000 per tahun. Formulir ini mendaftarkan minat preorder; pembayaran dan aktivasi diinformasikan kemudian.'],['Apakah otomatis diperpanjang?','Tidak. Akses berlaku 12 bulan sejak aktivasi dan dapat diperpanjang secara manual. Harga perpanjangan akan diinformasikan sebelum Anda memilih memperpanjang.'],['Bisa dipakai di HP?','Bisa melalui browser di ponsel, tablet, atau komputer. Gunakan bersama pendamping. Suara Indonesia, Inggris, Mandarin, dan Arab mengikuti suara yang tersedia di perangkat. Orang tua juga bisa merekam pertanyaan, nama gambar, dan respons dengan suaranya sendiri setelah masuk.'],['Bagaimana laporan hariannya?','Laporan mencatat jawaban benar, aktivitas selesai, dan kategori yang sering dipilih pada browser yang digunakan. Data bermain tersimpan di perangkat, belum tersinkron antarperangkat.']];
 return <div className="lf-landing"><nav className="lf-nav"><a href="/preorder" aria-label="Littlefinger Activities"><Brand/></a><a className="lf-demo-link" href="/#collection">Coba aktivitas <ArrowRight size={17}/></a></nav><main>
 <section className="lf-hero"><div className="lf-hero-copy"><span className="lf-kicker"><Leaf size={16}/> PREORDER AKSES TAHUNAN</span><h1>Jari kecil,<br/><em>banyak penemuan.</em></h1><p>Waktu bermain bersama jadi lebih mudah. Pilih aktivitas bergambar, dengarkan petunjuknya, lalu temukan hal baru bersama si kecil.</p><div className="lf-hero-actions"><a className="lf-primary" href="#daftar">Daftar preorder <ArrowRight size={19}/></a><span><del>Rp55.000</del><strong>Rp39.000 <small>/ tahun</small></strong></span></div><div className="lf-hero-note"><Check size={16}/> Sekali akses, bermain sepanjang tahun</div></div><div className="lf-hero-art"><img src="/assets/workbook/together.webp" alt="Ilustrasi ibu dan anak menikmati aktivitas bergambar bersama"/><div className="lf-art-caption"><Heart size={18}/> Sedikit waktu. Banyak cerita bersama.</div></div></section>
 <div className="lf-stat-strip"><span><strong>{catalogueStats.worksheets.toLocaleString('id-ID')}</strong> worksheet latihan</span><span><strong>{catalogueStats.categories}</strong> kategori</span><span><strong>{Object.keys(activityKinds).length}</strong> cara bermain</span><span><strong>4</strong> bahasa suara</span></div>
 <section className="lf-play-section"><div className="lf-section-title"><span className="eyebrow">PILIH SESUAI RASA INGIN TAHUNYA</span><h2>Hari ini, mau menemukan apa?</h2><p>Dari kendaraan dan angka sampai makanan, kebiasaan baik, serta peta dunia.</p></div><div className="lf-topic-samples">{[['car','Kendaraan','transport-play'],['apple','Angka & jumlah','count-to-5'],['food-nasi-goreng','Makanan','food-indonesia'],['earth','Negara & bendera','world-countries'],['habit-brushing','Kebiasaan baik','brush-teeth'],['weather-rainbow','Cuaca & musim','weather-signs']].map(([art,title,id])=><a key={art} href={'/#category/'+id}><Art name={art}/><span>{title}</span><ArrowRight size={15}/></a>)}</div><p className="lf-small-note">Jumlah worksheet mencakup variasi latihan. Coba koleksinya sebelum mendaftar.</p></section>
 <section className="lf-benefits">{[[BookIcon,'Banyak cara bermain','Pasangkan bayangan, pilih beberapa gambar, susun pola, lengkapi puzzle, dan jelajahi peta.'],[Volume2,'Dengarkan bersama','Petunjuk dan nama gambar bisa diputar dalam bahasa Indonesia, Inggris, Mandarin, dan Arab.'],[BarChart3,'Lihat langkah kecilnya','Laporan harian merangkum jawaban benar, bagian selesai, dan kategori yang sering dipilih.']].map(([Icon,title,copy],i)=>{const I=Icon as typeof Volume2;return <article key={i}><I size={24}/><h3>{title as string}</h3><p>{copy as string}</p></article>})}</section>
 <section className="lf-order-section" id="daftar"><div className="lf-offer"><span className="lf-kicker">HARGA PREORDER</span><h2>Satu tahun<br/>penuh rasa ingin tahu.</h2><del>Rp55.000 / tahun</del><div className="lf-price">Rp39.000<span>/ tahun</span></div><p className="lf-monthly">Setara Rp3.250/bulan · akses dibayar tahunan</p><ul><li><Check size={18}/> Akses tahunan sejak aktivasi</li><li><Check size={18}/> Dapat diperpanjang secara manual</li><li><Check size={18}/> Info peluncuran melalui WhatsApp</li></ul><p>Belum ada pembayaran di halaman ini. Jadwal peluncuran, cara pembayaran, dan aktivasi akan diinformasikan kemudian.</p></div><div className="lf-signup">{success?<div className="lf-success" role="status"><span className="lf-success-icon"><Check size={28}/></span><span className="lf-kicker">TERDAFTAR · BELUM MEMBAYAR</span><h2>Terima kasih, {name.trim()}!</h2><p>Minat preorder sudah tersimpan. Ikuti kabar peluncuran dan langkah berikutnya melalui grup WhatsApp.</p>{groupUrl?<a className="lf-primary" href={groupUrl} target="_blank" rel="noopener noreferrer"><MessageCircle size={20}/>Gabung grup WhatsApp</a>:<p className="lf-group-pending">Tautan grup sedang disiapkan. Pendaftaranmu tetap tersimpan; kabar berikutnya akan disampaikan melalui nomor WhatsApp yang kamu isi.</p>}<a className="lf-demo-link" href="/#collection">Sambil menunggu, coba aktivitas <ArrowRight size={17}/></a></div>:<form onSubmit={submit}><span className="lf-kicker">LANGKAH 1 DARI 2</span><h2>Ikut kabar peluncurannya.</h2><p>Daftarkan kontak orang tua, lalu bergabung ke grup WhatsApp.</p><label htmlFor="po-name">Nama orang tua</label><Input id="po-name" autoComplete="name" value={name} onChange={e=>setName(e.target.value)} required minLength={2} maxLength={80} placeholder="Nama panggilan atau nama lengkap"/><label htmlFor="po-wa">Nomor WhatsApp aktif</label><Input id="po-wa" type="tel" inputMode="tel" autoComplete="tel" value={whatsapp} onChange={e=>setWhatsApp(e.target.value)} required maxLength={25} placeholder="Contoh: 0812 3456 7890"/><small>Pastikan nomor ini bisa menerima pesan WhatsApp.</small><div className="po-trap" aria-hidden="true"><label>Website<Input name="website" tabIndex={-1} autoComplete="off"/></label></div><label className="lf-consent"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)} aria-label="Setuju menerima kabar preorder"/><span>Saya setuju nama dan nomor WhatsApp disimpan oleh Littlefinger Activities untuk kabar preorder, peluncuran, dan aktivasi. Saya bisa meminta berhenti menerima pesan.</span></label>{error&&<p role="alert" className="lf-error">{error}</p>}<Button className="lf-primary" type="submit" disabled={busy}>{busy?'Menyimpan…':'Daftar & lanjut ke grup'}<ArrowRight size={19}/></Button><p className="lf-form-note">Tidak ada tagihan otomatis. Data kontak tidak ditampilkan kepada pengunjung lain. Di grup WhatsApp, nomor dapat terlihat oleh anggota grup.</p></form>}</div></section>
 <section className="lf-roadmap"><Art name="sprout"/><div><span className="eyebrow">AKAN TERUS BERTUMBUH</span><h2>Masih banyak yang ingin kita jelajahi.</h2><p>Koleksi pengenalan Islami tersedia sebagai pilihan yang bisa diaktifkan orang tua. Eksplorasi dan praktik dilakukan bersama keluarga; koleksi akan terus dikembangkan.</p></div></section><section className="lf-faq"><h2>Sebelum ikut preorder</h2>{faq.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
 </main><footer className="lf-footer"><Brand/><p>Bermain dan belajar, ditemani orang tersayang.</p><a href="/admin">Pengelola</a></footer></div>;
}
function BookIcon(props:React.ComponentProps<typeof Heart>){return <Heart {...props}/>}
