'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,CheckCheck,ChevronLeft,ChevronRight,Eraser,Heart,Leaf,Pause,Pencil,Play,Printer,RotateCcw,Undo2,Volume2,Square,X} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {feedbackText} from '../data/personalization';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Art,PictureArt,Picture,pictureLabel,pictureDescription} from './artwork';
import {Worksheet,WorksheetState,worksheetInstruction} from '../data/workbook';
import {Lang,Settings,Text,textOf} from '../data/types';
import {AudioLanguagePicker,useNarration} from './narration';
import artLabels from '../data/art-labels.json';
import {activityKindLabel,getActivityKind} from '../data/activity-kinds';
import SpatialGame from './spatial-games';
import WorldMapGame from './world-map-game';
import {spatialComplete} from '../data/spatial-games';

const colors=['#55AE71','#EE5261','#F4C542','#328EE6','#9467D6','#EE8C3D','#EE8BAE','#976346','#333333'];
const colorNames=[['hijau','green'],['merah','red'],['kuning','yellow'],['biru','blue'],['ungu','purple'],['jingga','orange'],['merah muda','pink'],['cokelat','brown'],['hitam','black']];
function StoryEquation({a,listen}:{a:Worksheet;listen?:(value:Text,key:string)=>React.ReactNode}){
 if(!a.operands||!a.operation)return null;
 return <div className="story-equation" role="img" aria-label={a.expression}>{a.operands.map((value,i)=><div className="story-term" key={i}>{i===1&&<span className="story-operator">{a.operation==='add'?'+':'−'}</span>}<div className={listen?'spoken-quantity':''}><PictureArt item={{id:'operand-'+i,kind:'quantity',value,groupAsset:a.reference?.asset||'apple',label:{id:'',en:''}}}/><span className="story-number">{value}</span>{listen?.(pictureDescription({id:'operand-'+i,kind:'quantity',value,label:{id:'',en:''}}),'operand-'+i)}</div></div>)}<span className="story-operator">= ?</span></div>;
}
export function DrawingBoard({a,state,update,color,eraser}:{a:Worksheet;state:WorksheetState;update:(p:WorksheetState)=>void;color:string;eraser:boolean}){
 const [active,setActive]=useState<{color:string;points:string}|null>(null);const paths=state.paths||[];
 const point=(e:React.PointerEvent<SVGSVGElement>)=>{const r=e.currentTarget.getBoundingClientRect();return `${Math.round((e.clientX-r.left)*800/r.width)},${Math.round((e.clientY-r.top)*430/r.height)}`};
 const finish=()=>{if(active){update({paths:[...paths,active],checked:false});setActive(null)}};
 const guide=a.guide||a.trace;
 return <div className="draw-wrap"><svg viewBox="0 0 800 430" className="workbook-canvas" role="img" aria-label="Area menggambar dengan jari atau pensil" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);if(eraser){update({paths:paths.slice(0,-1)});return}setActive({color,points:point(e)})}} onPointerMove={e=>{if(active)setActive({...active,points:active.points+' '+point(e)})}} onPointerUp={finish} onPointerCancel={finish}>
 {a.canvas?<g className="draw-guides" transform="translate(113 0) scale(1.433333)">{a.canvas.guide.map((g,i)=>{const common={key:i,fill:g.fill||'none',stroke:g.stroke||'#a7b398',strokeWidth:g.strokeWidth||2,strokeDasharray:a.engine==='trace'||g.dashed?'5 5':undefined};if(g.kind==='line')return <line {...common} x1={g.x1} y1={g.y1} x2={g.x2} y2={g.y2}/>;if(g.kind==='circle')return <circle {...common} cx={g.cx} cy={g.cy} r={g.r}/>;if(g.kind==='path')return <path {...common} d={g.d}/>;if(g.kind==='trace-glyph')return <text {...common} x={g.x} y={(g.y||150)+((g.fontSize||140)*.34)} fontSize={g.fontSize} fontFamily="Nunito,sans-serif" fontWeight="700" textAnchor="middle">{g.text}</text>;if(g.kind==='shape-outline')return <g key={i} transform={`translate(${(g.cx||200)-(g.width||100)/2} ${(g.cy||150)-(g.height||100)/2})`}><foreignObject width={g.width} height={g.height}><div className="trace-outline"><PictureArt item={{id:'guide',shape:g.shape,label:{id:'',en:''}}}/></div></foreignObject></g>;if(g.kind==='asset')return <foreignObject key={i} x={g.x} y={g.y} width={g.width} height={g.height}><Art name={g.asset!}/></foreignObject>;if(g.kind==='pattern-strip')return <g key={i}>{g.items?.map((o,j)=><foreignObject key={j} x={(g.x||25)+j*(g.width||350)/(g.items?.length||1)} y={g.y||40} width={(g.width||350)/(g.items?.length||1)} height={65}><PictureArt item={o} small/></foreignObject>)}</g>;return null})}</g>:a.engine==='trace'&&<g fill="none" stroke="#c8cbbc" strokeWidth="4" strokeDasharray="8 10" strokeLinecap="round">{guide?.startsWith('M')?<path d={guide}/>:<text x="400" y="320" textAnchor="middle" fontSize="300">{guide||'∿'}</text>}</g>}
 {[...paths,...(active?[active]:[])].map((p,i)=>p.points.includes(' ')?<polyline key={i} points={p.points} fill="none" stroke={p.color} strokeWidth="7" strokeLinecap="round" strokeLinejoin="round"/>:<circle key={i} cx={p.points.split(',')[0]} cy={p.points.split(',')[1]} r="4" fill={p.color}/>)}</svg>
 <div className="drawing-access"><span>Atau buat cap:</span>{['circle','triangle','square'].map((shape,i)=><button key={shape} aria-label={'Cap '+['lingkaran','segitiga','persegi'][i]} onClick={()=>{const x=90+paths.length%6*110,y=90+Math.floor(paths.length/6)%3*120;const points=i===0?Array.from({length:25},(_,j)=>`${x+30*Math.cos(j*Math.PI/12)},${y+30*Math.sin(j*Math.PI/12)}`).join(' '):i===1?`${x},${y-30} ${x+30},${y+30} ${x-30},${y+30} ${x},${y-30}`:`${x-30},${y-30} ${x+30},${y-30} ${x+30},${y+30} ${x-30},${y+30} ${x-30},${y-30}`;update({paths:[...paths,{color,points}]})}}><PictureArt item={{id:shape,shape,color,label:{id:shape,en:shape}}} small/></button>)}<button className="icon-button" aria-label="Batalkan coretan terakhir" disabled={!paths.length} onClick={()=>update({paths:paths.slice(0,-1)})}><Undo2 size={20}/></button></div></div>
}

function MatchingLines({container,matches,options,right,pairs}:{container:React.RefObject<HTMLDivElement|null>;matches:string[];options:Picture[];right:Picture[];pairs?:{left:string;right:string}[]}){
 const [drawing,setDrawing]=useState<{width:number;height:number;paths:string[]}>({width:1,height:1,paths:[]});
 useEffect(()=>{
  const element=container.current;if(!element)return;
  const measure=()=>{const bounds=element.getBoundingClientRect(),columns=element.querySelectorAll('.pair-column');if(columns.length!==2)return;const leftButtons=columns[0].querySelectorAll('.pair-picture'),rightButtons=columns[1].querySelectorAll('.pair-picture');
   const paths=matches.map(id=>{const li=options.findIndex(o=>o.id===id),target=pairs?.find(p=>p.left===id)?.right||id,ri=right.findIndex(o=>o.id===target);if(!leftButtons[li]||!rightButtons[ri])return '';const l=leftButtons[li].getBoundingClientRect(),r=rightButtons[ri].getBoundingClientRect(),x1=l.right-bounds.left-8,x2=r.left-bounds.left+8,y1=l.top+l.height/2-bounds.top,y2=r.top+r.height/2-bounds.top,middle=(x1+x2)/2;return `M ${x1} ${y1} C ${middle} ${y1},${middle} ${y2},${x2} ${y2}`});
   setDrawing({width:bounds.width||1,height:bounds.height||1,paths});};
  measure();const observer=new ResizeObserver(measure);observer.observe(element);element.querySelectorAll('.choice-with-audio,.pair-picture').forEach(node=>observer.observe(node));window.addEventListener('resize',measure);return()=>{observer.disconnect();window.removeEventListener('resize',measure)};
 },[container,matches,options,right,pairs]);
 return <svg viewBox={`0 0 ${drawing.width} ${drawing.height}`} className="matching-lines" aria-hidden="true">{drawing.paths.map((d,i)=><path key={matches[i]} d={d} stroke={colors[i%colors.length]} fill="none" strokeWidth="4" strokeLinecap="round"/>)}</svg>;
}

export default function WorkbookPlayer({a,state,update,settings,onNext,onPrevious,onLibrary,onObserve,onFavorite,isFavorite,onMute,onSettingsChange,onLearning}:{a:Worksheet;state:WorksheetState;update:(s:WorksheetState)=>void;settings:Settings;onNext:()=>void;onPrevious:()=>void;onLibrary:()=>void;onObserve:()=>void;onFavorite:()=>void;isFavorite:boolean;onMute:(mute:boolean)=>void;onSettingsChange:(p:Partial<Settings>)=>void;onLearning?:(type:"attempt"|"mistake"|"complete",correct?:boolean,signature?:string)=>void}){
 const l=settings.lang,t=(id:string,en:string)=>l==='id'?id:en;const [feedback,setFeedbackValue]=useState('');const [feedbackKind,setFeedbackKind]=useState<''|'retry'|'success'|'creative'>('');const setFeedback=(value:string)=>{setFeedbackKind('');setFeedbackValue(value)};const [color,setColor]=useState(colors[0]);const [eraser,setEraser]=useState(false);const [chosenSticker,setChosenSticker]=useState('');const [finished,setFinished]=useState(false);const [pause,setPause]=useState(false);const [help,setHelp]=useState(false);const [pending,setPending]=useState('');
 const selected=state.selected||[],matches=state.matches||[],flipped=state.flipped||[],options=a.options;const complete=!!state.complete;const sheetRef=useRef<HTMLDivElement>(null);const pairRef=useRef<HTMLDivElement>(null);const elapsed=useRef(state.seconds||0);const updateRef=useRef(update);updateRef.current=update;
 useEffect(()=>{const onHide=()=>{if(document.hidden){setPause(true);window.speechSynthesis?.cancel()}};document.addEventListener('visibilitychange',onHide);return()=>{document.removeEventListener('visibilitychange',onHide);window.speechSynthesis?.cancel()}},[]);
 useEffect(()=>{if(pause||complete)return;const id=setInterval(()=>{elapsed.current++;if(elapsed.current>0&&elapsed.current%(Number(settings.limit)*60)===0)setPause(true)},1000);return()=>{clearInterval(id);updateRef.current({seconds:elapsed.current})}},[pause,complete,settings.limit]);
 const [resetNonce,setResetNonce]=useState(0);
 const voice=useNarration(settings,onMute);
 useEffect(()=>{if(pause)voice.stop()},[pause,voice.stop]);
 const response=feedbackKind?feedbackText(settings.nickname,feedbackKind):null;
 const respond=(kind:'retry'|'success'|'creative')=>{setFeedbackValue('');setFeedbackKind(kind);if(!settings.mute)void voice.play(feedbackText(settings.nickname,kind),'feedback')};
 const audioButton=(value:Text,key:string)=>voice.audio(value,key);
 const reset=()=>{setResetNonce(n=>n+1);voice.stop();elapsed.current=0;update({sorted:{},selected:[],matches:[],flipped:[],counted:[],paths:[],complete:false,checked:false,stickers:[],seconds:0,observation:''});setFeedback('');setPending('');setFinished(false);setChosenSticker('')};
 const speak=()=>voice.play(worksheetInstruction(a),'instruction');
 const select=(id:string)=>{if(complete)return;setFeedback('');update({selected:selected.includes(id)?selected.filter(x=>x!==id):(['count','compare','pattern','map'].includes(a.engine)||['choose-one','clue','odd-one-out','picture-detail'].includes(getActivityKind(a)))?[id]:[...selected,id],checked:false})};
 const check=()=>{if(complete){setFinished(true);return}let correct=false;
 if(['identify','compare','pattern','map'].includes(a.engine))correct=selected.length===a.answer.length&&a.answer.every(x=>selected.includes(x));
 if(a.engine==='count')correct=selected.length===a.answer.length&&a.answer.every(x=>selected.includes(x));
 if(a.engine==='pair'||a.engine==='memory')correct=matches.length===options.length;
 if(a.engine==='sort')correct=options.length>0&&options.every(o=>{const target=a.pairs?.find(p=>p.left===o.id)?.right;return !!target&&state.sorted?.[o.id]===target});
 if(a.engine==='sequence')correct=selected.join('|')===a.answer.join('|');
 if(['puzzle','placement','route'].includes(a.engine))correct=spatialComplete(a,state);
 if(a.engine==='draw'||a.engine==='trace')correct=(state.paths?.length||0)>0;
 if(a.engine==='explore')correct=selected.length>0;
 const creative=['draw','trace','explore'].includes(a.engine);const meaningful=selected.length||matches.length||Object.keys(state.sorted||{}).length||state.paths?.length||state.counted?.length;
 if(meaningful&&!creative)onLearning?.('attempt',correct,JSON.stringify({selected:a.engine==='sequence'?selected:[...selected].sort(),matches:[...matches].sort(),sorted:Object.entries(state.sorted||{}).sort()}));
 if(correct)onLearning?.('complete');
 if(correct){update({complete:true,checked:true});respond(creative?'creative':'success');setFinished(true)}else{update({checked:true});respond('retry')}
 };
 const rightOptions=a.rightOptions||options.map(o=>o.pairSymbol?{...o,symbol:o.pairSymbol,asset:undefined,shape:undefined,label:o.pairLabel||o.label}:o);
 const right=[...rightOptions].reverse();
 const match=(id:string)=>{if(matches.includes(pending)||complete)return;const target=a.pairs?.find(p=>p.left===pending)?.right||pending;if(!pending){setFeedback(t('Pilih gambar di kiri dahulu.','Choose a picture on the left first.'));return}if(target===id){update({matches:[...matches,pending],checked:false});setPending('');setFeedback(t('Pasangannya ketemu!','You found a pair!'))}else{onLearning?.('mistake',false,pending+'-'+id);respond('retry')}};
 const addSticker=(asset:string,x:number,y:number)=>{update({stickers:[...(state.stickers||[]).slice(-11),{asset,x,y}]});setChosenSticker('')};
 const optionButton=(o:Picture,i:number,extras:Record<string,unknown>={})=>{
  const spokenLang=a.languageOfTask==='id'?'id':l;
  const label=pictureLabel(o,spokenLang,i);
  return <div className="choice-with-audio" key={o.id}><button className={'picture-choice '+(selected.includes(o.id)?'circled':'')} aria-label={label} aria-pressed={selected.includes(o.id)} disabled={complete} onClick={()=>select(o.id)} {...extras}><PictureArt item={o}/>{selected.includes(o.id)&&<span className="pencil-ring" style={{borderColor:color}}/>}<span className="object-caption">{o.showLabel===false||o.silhouette||o.kind==='quantity'||o.kind==='measurement'||o.kind==='arrow'?'':textOf(o.label,spokenLang)}</span></button>{o.showLabel!==false&&!o.silhouette&&voice.translated&&voice.text(pictureDescription(o,i))!==textOf(o.label,spokenLang)&&<span lang={voice.textLang} dir={voice.textDirection} className="translation-caption">{voice.text(pictureDescription(o,i))}</span>}{audioButton(pictureDescription(o,i),'choice-'+o.id)}</div>;
 };
 const putInBin=(bin:string,option=pending)=>{if(!option||complete)return;update({sorted:{...state.sorted,[option]:bin},checked:false});setPending('');setFeedback(t('Sudah dipindahkan. Boleh diubah lagi.','Placed. You can move it again.'))};

 const renderGame=()=>{
 if(a.engine==='explore')return <div className="explore-game"><p className="explore-note">{t('Bersama pendamping: lakukan di luar layar, lalu tandai yang benar-benar dicoba. Boleh berhenti kapan saja.','With a grown-up: try away from the screen, then mark what you actually tried. Stop whenever you wish.')}</p>{options.map((o,i)=><div className="explore-step" key={o.id}><Checkbox id={'step-'+o.id} checked={selected.includes(o.id)} disabled={complete} onCheckedChange={()=>select(o.id)}/><label htmlFor={'step-'+o.id}>{o.asset&&<Art name={o.asset}/>}<span>{textOf(o.label,l)}{voice.translated&&<small lang={voice.textLang} dir={voice.textDirection}>{voice.text(o.label)}</small>}</span></label>{audioButton(o.label,'explore-'+o.id)}</div>)}<label className="explore-observation">{t('Apa yang diamati? (opsional)','What did you notice? (optional)')}<textarea value={state.observation||''} maxLength={500} onChange={e=>update({observation:e.target.value})} rows={3}/></label>{a.completion?.goals?.map((g,i)=><div className="explore-goal" key={i}><p>{textOf(g,l)}</p>{audioButton(g,'goal-'+i)}</div>)}</div>;

 if(a.engine==='map')return <WorldMapGame a={a} state={state} onSelect={select} l={l} listen={audioButton} translation={voice.translated?{text:voice.text,lang:voice.textLang,dir:voice.textDirection}:undefined}/>;
 if(['puzzle','placement','route'].includes(a.engine))return <SpatialGame key={a.id+'-'+resetNonce} a={a} state={state} update={update} l={l} listen={audioButton}/>;
 if(['identify','compare','pattern'].includes(a.engine))return <>{a.operands&&a.operation?<StoryEquation a={a} listen={audioButton}/>:a.reference&&<div className="example-reference"><span>{getActivityKind(a)==='picture-detail'?t('Lihat potongannya','Look at the detail'):t('Contoh','Example')}</span><span className="reference-with-audio"><span role="img" aria-label={textOf(a.reference.label,l)}><PictureArt item={a.reference} small/></span>{audioButton(pictureDescription(a.reference),'reference')}</span></div>}{a.engine==='pattern'&&<div className="workbook-pattern" role="group" aria-label={t('Pola gambar; geser untuk melihat seluruhnya','Picture pattern; scroll to see all')}>{(a.patternItems||a.pattern?.map(id=>options.find(x=>x.id===id)||null)||[]).map((item,i)=><div className={'pattern-piece '+(!item?'missing':'')} key={i} aria-label={item?textOf(item.label,l):t('Gambar yang hilang','Missing picture')}>{item?<><PictureArt item={item}/>{audioButton(pictureDescription(item,i),'pattern-'+i)}</>:<span>?</span>}</div>)}</div>}<div className={'picture-grid '+(a.layout==='fixed-3-by-3'?'position-grid':a.layout==='story-choices'?'story-choices':'')+(a.operands&&a.operation?' story-number-choices':'')+(options.length===2?' two-options':options.length===3?' three-options':'')} >{options.map((o,i)=>optionButton(o,i))}</div></>;
 if(a.engine==='count'){const counted=state.counted||[],asset=a.countAsset||'apple',item={id:'counter',asset,label:(artLabels as Record<string,Text>)[asset]||{id:'Gambar',en:'Picture',zh:'图片'}},total=a.operation==='subtract'?a.operands?.[0]||0:a.countTarget||0;return <><div className={'count-pictures '+(a.operation==='add'?'addition-pictures':'')}>{Array.from({length:total},(_,i)=>{const removed=a.operation==='subtract'&&i>=(a.countTarget||0);return <span className="count-item-wrap" key={i}>{a.operation==='add'&&i===(a.operands?.[0]||0)&&<span className="addition-sign">{i===0?'0 +':'+'}</span>}<button key={i} aria-label={removed?t('Gambar yang diambil','Removed picture'):t('Hitung gambar ','Count picture ')+(i+1)} disabled={complete||removed||counted.includes(String(i))} className={'count-picture '+(removed?'removed ': '')+(counted.includes(String(i))?'counted':'')} onClick={()=>update({counted:[...counted,String(i)]})}><PictureArt item={item}/>{counted.includes(String(i))&&<b>{counted.indexOf(String(i))+1}</b>}</button>{audioButton(item.label,'count-item-'+i)}{a.operation==='add'&&i===total-1&&a.operands?.[1]===0&&<span className="addition-sign">+ 0</span>}</span>})}</div>{total===0&&<div className="zero-basket">{t('Tidak ada gambar tersisa.','No pictures are left.')}</div>}{a.expression&&<div className="math-expression">{a.expression}</div>}<div className="number-choices">{options.map((o,i)=>optionButton(o,i))}</div></>}
 if(a.engine==='pair')return <div className="workbook-pairs" ref={pairRef}><MatchingLines container={pairRef} matches={matches} options={options} right={right} pairs={a.pairs}/><div className="pair-column">{options.map((o,i)=>optionButton(o,i,{className:'picture-choice pair-picture '+(pending===o.id?'is-pending':'')+(matches.includes(o.id)?' is-matched':''),disabled:complete||matches.includes(o.id),'aria-pressed':pending===o.id,onClick:()=>{setPending(o.id);setFeedback(t('Sekarang pilih pasangannya.','Now choose its partner.'))},draggable:true,onDragStart:(e:React.DragEvent)=>{setPending(o.id);e.dataTransfer.setData('text/plain',o.id)}}))}</div><div className="pair-column">{right.map((o,i)=>optionButton(o,i,{className:'picture-choice pair-picture '+(matches.some(id=>(a.pairs?.find(p=>p.left===id)?.right||id)===o.id)?'is-matched':''),disabled:complete||matches.some(id=>(a.pairs?.find(p=>p.left===id)?.right||id)===o.id),'aria-pressed':undefined,onClick:()=>match(o.id),onDragOver:(e:React.DragEvent)=>e.preventDefault(),onDrop:(e:React.DragEvent)=>{e.preventDefault();match(o.id)}}))}</div></div>;
 if(a.engine==='sort')return <div className="sorting-game"><p className="sorting-hint">{t('Ketuk gambar, lalu pilih tempatnya.','Tap a picture, then choose its group.')}</p><div className="sorting-options">{options.map((o,i)=>optionButton(o,i,{className:'picture-choice sort-picture '+(pending===o.id?'is-pending':''),'aria-pressed':pending===o.id,onClick:()=>setPending(o.id),draggable:!complete,onDragStart:(e:React.DragEvent)=>{setPending(o.id);e.dataTransfer.setData('text/plain',o.id)}}))}</div><div className="sorting-bins">{a.bins?.map(bin=><div className="sort-bin" key={bin.id} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');if(options.some(o=>o.id===id))putInBin(bin.id,id)}}><div className="sort-bin-heading"><button className="sort-target" disabled={complete||!pending} onClick={()=>putInBin(bin.id)} aria-label={t('Letakkan di ','Place in ')+textOf(bin.label,l)}><Art name={bin.asset}/><span>{textOf(bin.label,l)}</span></button>{audioButton(bin.label,'bin-'+bin.id)}</div><div className="sorted-items">{options.filter(o=>state.sorted?.[o.id]===bin.id).map(o=><button key={o.id} disabled={complete} aria-label={t('Pindahkan ','Move ')+textOf(o.label,l)} onClick={()=>{setPending(o.id);setFeedback(t('Pilih tempat baru untuk gambar ini.','Choose a new group for this picture.'))}}><PictureArt item={o} small/><span>{textOf(o.label,l)}</span></button>)}</div></div>)}</div></div>;
 if(a.engine==='sequence')return <><div className="order-slots">{a.answer.map((id,i)=><button key={i} className="order-slot" aria-label={t('Kosongkan urutan ','Clear position ')+(i+1)} disabled={complete||!selected[i]} onClick={()=>update({selected:selected.slice(0,i),checked:false})}><small>{i+1}</small>{selected[i]&&options.some(o=>o.id===selected[i])?<PictureArt item={options.find(o=>o.id===selected[i])!}/>:<span>···</span>}</button>)}</div><div className="picture-grid sequence-options">{[...options].reverse().map((o,i)=>optionButton(o,i,{disabled:complete||selected.includes(o.id),onClick:()=>{update({selected:[...selected,o.id],checked:false});setFeedback('')}}))}</div></>;
 if(a.engine==='memory'){const deck=[...options,...[...options].reverse()],mismatch=flipped.length===2&&deck[flipped[0]].id!==deck[flipped[1]].id;return <><div className="workbook-memory">{deck.map((o,i)=>{const visible=flipped.includes(i)||matches.includes(o.id);return <div className="memory-with-audio" key={i}><button aria-label={visible?textOf(o.label,l):t('Buka kartu ','Turn card ')+(i+1)} className={'memory-tile '+(visible?'face-up':'')} disabled={visible||flipped.length===2||complete} onClick={()=>{const v=[...flipped,i];if(v.length===2&&deck[v[0]].id===o.id){update({matches:[...matches,o.id],flipped:[]});setFeedback(t('Sepasang kartu yang sama!','A matching pair!'))}else{if(v.length===2){onLearning?.('mistake',false,v.join('-'));respond('retry')}update({flipped:v})}}}>{visible?<PictureArt item={o}/>:<Art name="leaf"/>}</button>{visible&&audioButton(pictureDescription(o,i),'memory-'+i)}</div>})}</div>{mismatch&&<button className="soft-button memory-retry" onClick={()=>update({flipped:[]})}><RotateCcw size={17}/>{t('Tutup & coba lagi','Turn over & try again')}</button>}</>}
 if(a.engine==='trace'||a.engine==='draw')return <><DrawingBoard a={a} state={state} update={update} color={color} eraser={eraser}/>{!!a.canvas?.guide.some(g=>g.kind==='asset')&&<div className="drawing-object-labels">{[...new Set(a.canvas.guide.filter(g=>g.kind==='asset').map(g=>g.asset!))].map(asset=><div key={asset}><span>{textOf((artLabels as Record<string,Text>)[asset],l)}</span>{audioButton((artLabels as Record<string,Text>)[asset]||{id:'Gambar',en:'Picture',zh:'图片'},'guide-'+asset)}</div>)}</div>}{a.completion?.goals&&<p className="draw-goals">{a.completion.goals.map(g=>textOf(g,l)).join(' ')}</p>}</>;
 return <div className="empty-state">{t('Pilih lembar lain untuk bermain.','Choose another worksheet.')}</div>;
 };
 return <div className="workbook-view"><div className="workbook-breadcrumb"><button onClick={onLibrary}><ArrowLeft size={16}/>{t('Aktivitas','Activities')}</button><span>/</span><span>{activityKindLabel(a,l)}</span><button className="print-action" aria-label={t('Cetak lembar','Print worksheet')} onClick={()=>window.print()}><Printer size={16}/><span>{t('Cetak lembar','Print worksheet')}</span></button></div>
 <AudioLanguagePicker settings={settings} onChange={onSettingsChange}/><div className="paper-and-stickers"><div className="paper-column"><section className={'worksheet-paper '+(chosenSticker?'placing-sticker':'')} ref={sheetRef} onClickCapture={e=>{if(!chosenSticker||(e.target as HTMLElement).closest('[data-voice-control]'))return;const r=e.currentTarget.getBoundingClientRect();e.stopPropagation();e.preventDefault();addSticker(chosenSticker,Math.min(92,Math.max(8,(e.clientX-r.left)/r.width*100)),Math.min(94,Math.max(10,(e.clientY-r.top)/r.height*100)))}}>
 <i className="washi left" aria-hidden="true"/><i className="washi right" aria-hidden="true"/>
 <header className="paper-heading"><div><span className="activity-kind-label">{activityKindLabel(a,l)}</span><h1>{textOf(a.title,l)}</h1><div className="paper-instruction"><div><p>{voice.question(worksheetInstruction(a),l)}</p>{voice.translated&&<p className="instruction-translation" lang={voice.textLang} dir={voice.textDirection}>{voice.question(worksheetInstruction(a))}</p>}</div><button data-voice-control onClick={speak} aria-pressed={voice.activeKey==='instruction'} aria-label={t('Dengarkan petunjuk','Listen to the instruction')}>{voice.activeKey==='instruction'?<Square size={17}/>:<Volume2 size={19}/>}</button>{voice.record(worksheetInstruction(a),'instruction')}</div></div><span className="child-name">{t('Nama','Name')}: <em>{settings.nickname==='Little explorer'?t('Teman kecil','Little friend'):settings.nickname||'…'}</em></span></header>
 {voice.status}{getActivityKind(a)==='choose-many'&&<p className="selection-guide" role="status">{t('Boleh pilih lebih dari satu. Ketuk lagi untuk membatalkan.','Choose more than one. Tap again to undo.')} <strong>{selected.length} {t('dipilih','selected')}</strong></p>}
 <div className={'game-board engine-'+a.engine}>{renderGame()}</div>
 <div className="paper-progress"><div aria-label={t('Kemajuan aktivitas','Activity progress')}>{(a.engine==='count'?Array.from({length:a.countTarget||1},(_,i)=>String(i)):['pair','memory','sort','puzzle','placement'].includes(a.engine)?options.map(o=>o.id):a.answer).map((id,i)=><span key={i} className={(complete||(['sort','puzzle','placement'].includes(a.engine)?!!state.sorted?.[id]:a.engine==='pair'||a.engine==='memory'?matches.includes(id):selected.includes(id)))?'filled':''}/>)}</div><span className="worksheet-number">{a.id==='telur-dan-hewan'?'01':a.id.split('-').at(-1)}</span><button className={'favorite-button '+(isFavorite?'saved':'')} onClick={onFavorite} aria-label={t(isFavorite?'Hapus dari favorit':'Simpan ke favorit',isFavorite?'Remove from favorites':'Save to favorites')} aria-pressed={isFavorite}><Heart size={20} fill={isFavorite?'currentColor':'none'}/></button></div>
 {(state.stickers||[]).map((s,i)=><span className="placed-sticker" key={i} style={{left:s.x+'%',top:s.y+'%',transform:`translate(-50%,-50%) rotate(${i%2?10:-9}deg)`}}><Art name={s.asset}/></span>)}
 </section>
 <div className="workbook-feedback" role="status" aria-live="polite">{chosenSticker?t('Ketuk lembar untuk menempel stiker.','Tap the sheet to place your sticker.'):(response?voice.text(response):feedback)|| (complete?t('Lembar ini sudah selesai. Boleh coba lagi kapan saja.','This sheet is complete. You can try it again anytime.'):'')}</div>
 {settings.recordMode&&<div className="feedback-recorders"><span>{t('Rekam respons untuk anak','Record responses for your child')}</span>{(['retry','success','creative'] as const).map(kind=><span key={kind}>{t(kind==='retry'?'Coba lagi':kind==='success'?'Jawaban benar':'Kreasi selesai',kind==='retry'?'Try again':kind==='success'?'Correct answer':'Creative finish')}{voice.record(feedbackText(settings.nickname,kind))}</span>)}</div>}<div className="worksheet-tools"><button className="tool-button" onClick={reset}><RotateCcw size={20}/><span>{t('Ulangi','Again')}</span></button>{['draw','trace'].includes(a.engine)?<><button className={'tool-button icon-tool '+(!eraser?'selected-tool':'')} onClick={()=>setEraser(false)} aria-label={t('Pensil','Pencil')}><Pencil color="#cd8665"/></button><button className={'tool-button icon-tool '+(eraser?'selected-tool':'')} onClick={()=>setEraser(true)} aria-label={t('Penghapus','Eraser')}><Eraser color="#759eaf"/></button></>:<button className="tool-button icon-tool" onClick={()=>{update({selected:[],checked:false});setFeedback('')}} disabled={complete||!selected.length} aria-label={t('Hapus pilihan','Erase selection')}><Eraser color="#759eaf"/></button>}<button className="finish-button" onClick={check}>{complete?<CheckCheck size={21}/>:null}{t('Selesai','Done')}<Art name="flower"/></button><button className="pause-button" aria-label={t('Jeda bermain','Pause play')} onClick={()=>setPause(true)}><Pause size={19}/></button></div>
 {['draw','trace'].includes(a.engine)&&<div className="pencil-colors">{colors.map((c,i)=><button key={c} style={{background:c}} title={colorNames[i][l==='id'?0:1]} aria-label={t('Warna ','Color ')+colorNames[i][l==='id'?0:1]} aria-pressed={color===c} onClick={()=>{setColor(c);setEraser(false)}}/>)}</div>}
 <div className="sheet-pagination"><button onClick={onPrevious}><ChevronLeft size={18}/>{t('Sebelumnya','Previous')}</button><button onClick={()=>setHelp(true)}>{t('Coba bersama Bunda','A little help')}</button><button onClick={onNext}>{t('Lanjut bermain','Keep playing')}<ChevronRight size={18}/></button></div>
 </div>
 {settings.stickers&&<aside className="sticker-tray"><h2>{t('Stikerku','My stickers')} <span>♥</span></h2><div className="sticker-list">{['sun','flower','leaf','butterfly','star'].map(asset=><button key={asset} className={'sticker-button '+(chosenSticker===asset?'picked':'')} aria-label={t('Pilih stiker ','Choose sticker ')+({sun:'matahari',flower:'bunga',leaf:'daun',butterfly:'kupu-kupu',star:'bintang'} as Record<string,string>)[asset]} aria-pressed={chosenSticker===asset} onClick={()=>setChosenSticker(chosenSticker===asset?'':asset)}><Art name={asset}/></button>)}</div>{chosenSticker?<><button className="sticker-place" onClick={()=>addSticker(chosenSticker,88,86)}>{t('Tempel di sudut','Place in corner')}</button><button className="text-button" onClick={()=>setChosenSticker('')}>{t('Batal','Cancel')}</button></>:<p>{t('Pilih, lalu tempel','Choose & place')}</p>}{!!state.stickers?.length&&<button className="sticker-place" onClick={()=>update({stickers:state.stickers!.slice(0,-1)})}><Undo2 size={14}/>{t('Lepas satu','Undo')}</button>}</aside>}
 </div>
 <Dialog open={finished} onOpenChange={setFinished}><DialogContent className="completion-dialog"><Art name="sun"/><DialogTitle>{t('Satu penemuan kecil!','One little discovery!')}</DialogTitle><DialogDescription lang={voice.textLang} dir={voice.textDirection}>{voice.text(feedbackText(settings.nickname,['draw','trace','explore'].includes(a.engine)?'creative':'success'))}</DialogDescription>{voice.audio(feedbackText(settings.nickname,['draw','trace','explore'].includes(a.engine)?'creative':'success'),'feedback-success')}<div className="offline-invitation"><Leaf size={22}/><p>{textOf(a.offscreen,l)||t('Bersama pendamping, cari bentuk atau benda yang mirip di sekitarmu. Letakkan perangkat saat bermain.','With a grown-up, find similar shapes or objects around you. Put the device down while playing.')}</p></div><button className="finish-button" onClick={()=>{setFinished(false);onNext()}}>{t('Lanjut bermain','Keep playing')}<ArrowRight size={18}/></button><div className="inline-controls"><button className="text-button" onClick={()=>{setFinished(false);setPause(true)}}>{t('Istirahat dulu','Take a break')}</button><button className="text-button" onClick={()=>{setFinished(false);onObserve()}}>{t('Catatan Bunda','Caregiver note')}</button></div></DialogContent></Dialog>
 <Dialog open={pause} onOpenChange={setPause}><DialogContent className="completion-dialog"><Art name="moon"/><DialogTitle>{t('Boleh istirahat dulu.','A little pause is lovely.')}</DialogTitle><DialogDescription>{t('Coretan dan pilihanmu tersimpan di perangkat ini. Lanjutkan saat kamu ingin.','Your marks and choices are saved on this device. Come back when you want to.')}</DialogDescription><button className="finish-button" onClick={()=>setPause(false)}><Play size={18}/>{t('Lanjut bermain','Keep playing')}</button><button className="text-button" onClick={()=>{setPause(false);onLibrary()}}>{t('Lihat koleksi','View collection')}</button></DialogContent></Dialog>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent><DialogTitle>{t('Coba bersama, pelan-pelan.','Take your time together.')}</DialogTitle><DialogDescription>{textOf(a.instruction,l)}</DialogDescription><p>{t('Contohkan satu pilihan, lalu beri anak giliran. Pada aktivitas pasangan, ketuk gambar kiri lalu pasangannya di kanan. Tidak perlu cepat. Boleh melewati lembar kapan saja.','Model one choice, then give your child a turn. For matching, tap the left picture and then its partner on the right. There is no rush; you can skip a sheet anytime.')}</p><p>{textOf(a.note,l)}</p><p>{textOf(a.offscreen,l)||t('Setelah mencoba, cari benda serupa bersama pendamping. Pilih benda besar dan aman, lalu letakkan layar.','After trying, find similar large, safe objects with a grown-up. Put the screen away.')}</p><button className="finish-button" onClick={()=>setHelp(false)}>{t('Kembali bermain','Back to play')}</button></DialogContent></Dialog>
 <div className={'print-workbook engine-'+a.engine}><div className="print-brand">Littlefinger Activities · {t('Buku aktivitasku','My activity book')}</div><h1>{textOf(a.title,l)}</h1><p>{textOf(a.instruction,l)}</p><div className="print-name">{t('Nama','Name')}: ____________________</div>{a.operands&&a.operation?<StoryEquation a={a}/>:a.reference&&<div className="print-pattern"><PictureArt item={a.reference}/></div>}{a.engine==='pattern'&&<div className="print-pattern">{a.patternItems?.map((o,i)=>o?<PictureArt key={i} item={o}/>:<span key={i}>?</span>)}</div>}{a.engine==='map'&&<WorldMapGame a={a} state={{}} onSelect={()=>{}} l={l} print/>}{['puzzle','placement','route'].includes(a.engine)&&<SpatialGame a={a} state={{}} update={()=>{}} l={l} print/>}<div className={'print-options '+(a.engine==='pair'?'print-pairs':'')}>{(['puzzle','placement','route','map'].includes(a.engine)?[]:a.engine==='memory'?[...options,...options]:a.engine==='count'?Array.from({length:a.operation==='subtract'?(a.operands?.[0]||0):(a.countTarget||0)},()=>({id:'count',asset:a.countAsset||'apple',label:{id:'',en:''}})):options).map((o,i)=><div key={i} className={a.engine==='count'&&a.operation==='subtract'&&i>=(a.countTarget||0)?'removed':''}><PictureArt item={o}/>{a.engine!=='count'&&<span>{textOf(o.label,a.languageOfTask==='id'?'id':l)}</span>}</div>)}{a.engine==='pair'&&<div className="print-right">{right.map((o,i)=><div key={i}><PictureArt item={o}/><span>{textOf(o.label,l)}</span></div>)}</div>}</div>{a.engine==='count'&&<>{a.expression&&<div className="math-expression">{a.expression}</div>}<div className="print-answers">{options.map(o=><span key={o.id}>{o.symbol}</span>)}</div></>}{a.engine==='sort'&&<div className="print-sort-bins">{a.bins?.map(bin=><div key={bin.id}><Art name={bin.asset}/><h2>{textOf(bin.label,l)}</h2></div>)}</div>}{['draw','trace'].includes(a.engine)&&<DrawingBoard a={a} state={{}} update={()=>{}} color={colors[0]} eraser={false}/>}<footer>{t('Coba bersama pendamping · Boleh diulang kapan saja','Try with a grown-up · Repeat whenever you like')}</footer></div>
 </div>
}
