import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
raw=json.loads((root/'content/activities.json').read_text())
engines={'identify':'tap-identify','pair':'picture-pair','sort':'sort','sequence':'sequence','count':'count-one-to-one','compare':'compare-quantity','pattern':'pattern','memory':'memory-pairs','draw':'open-drawing','trace':'trace-path','checklist':'practical-life','story':'guided-story'}
packs={'little-discoveries':'shapes-colors-size','abc-and-words':'alphabet-sounds','numbers-and-shapes':'early-math','everyday-adventures':'practical-life','feelings-and-friends':'social-emotional','ready-for-school':'kindergarten-readiness','rainy-day-play':'rainy-day','nature-noticing':'nature-weather'}
common=[]
for a in raw:
 en=lambda x:a[x]['en']
 r={'id':a['id'],'version':a['version'],'title':a['title'],'packId':packs[a['pack']],'ageRangeMonths':{'min':int(a['age'])*12,'max':int(a['age'])*12+11},'readinessNotes':['Navigation starting point only; not a developmental assessment.',en('adaptation')],'skills':{'primary':a['engine'],'secondary':['caregiver-conversation','real-world-exploration']},'learningObjective':en('objective'),'mode':'hybrid','engine':engines[a['engine']],'engineConfig':{k:a[k] for k in ['options','answer','groups','steps','pattern','countTarget','traceShape','traceLetter'] if k in a},'materials':[{'name':en('materials'),'adultPreparation':en('safety')}],'steps':[{'id':'discover','kind':'discover','instruction':a['instruction'],'caregiverNote':'Caregiver-selected draft demo. Language and educational review pending.','demonstration':en('adaptation')},{'id':'try','kind':'try','instruction':a['prompt'],'caregiverNote':'Model one turn; simplify or stop freely.','demonstration':'An adult may demonstrate the stated task.'},{'id':'do','kind':'do','instruction':a['offscreen'],'caregiverNote':en('safety'),'demonstration':'Prepare materials, put the device away, then explore together.'}],'completionPolicy':a['completionPolicy'],'feedback':{'onAccepted':{'en':'You explored it.','id':'Kamu sudah mencoba.'},'onRetry':{'en':'Take another look together.','id':'Lihat lagi bersama.'},'onStop':{'en':'It is okay to stop.','id':'Boleh berhenti.'}},'realWorldTransfer':{'invitation':en('offscreen'),'deviceAway':True,'caregiverObservationOptional':True,'screenDoesNotProve':['Real-world mastery','Developmental milestone attainment']},'safety':{'adultSupervision':'co-play','hazards':[en('safety')],'avoidMaterials':['water beads','button batteries','small loose magnets','loose rice, beans or beads'],'alternative':en('adaptation'),'reviewStatus':'not-reviewed'},'assetIds':[],'audioAssetIds':[],'sources':[],'contentType':'general','review':{'editorialStatus':'not-reviewed','editorialReviewer':None,'editorialReviewedAt':None,'religiousStatus':'not-applicable','religiousReviewer':None,'religiousReviewedAt':None},'delivery':{'publication':'adult-demo','implementation':'working','tests':'not-tested','assets':'ready','rights':'unverified'}}
 common.append(r)
(root/'public/specs/catalogue-common.json').write_text(json.dumps(common,ensure_ascii=False,indent=2)+'\n')
(root/'public/specs/activities.json').write_text(json.dumps(raw,ensure_ascii=False,indent=2)+'\n')
print(f'Exported {len(common)} draft records under supplied common contract')
